# Generated by Django 3.2.5 on 2022-04-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                # ('date', models.DateField()),
                # ('time', models.TimeField()),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(default='NA')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('disambiguator', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=225)),
                ('textbook_or_not', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('nation_id', models.AutoField(primary_key=True, serialize=False)),
                ('nation', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate_sequence', models.IntegerField(unique=True)),
                ('rate_name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('systemuser_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('disambiguator', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Write',
            fields=[
                ('written_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writes', to='webinfo.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writes', to='webinfo.book')),
            ],
        ),
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('prefer_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prefers', to='webinfo.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prefers', to='webinfo.systemuser')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=255)),
                ('content', models.TextField(default='NA')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='webinfo.book')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='webinfo.rate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='webinfo.systemuser')),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('participate_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participates', to='webinfo.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participates', to='webinfo.systemuser')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likes', to='webinfo.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likes', to='webinfo.systemuser')),
            ],
        ),
        migrations.CreateModel(
            name='Explain',
            fields=[
                ('explain_id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='explains', to='webinfo.book')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='explains', to='webinfo.type')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='webinfo.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='webinfo.systemuser')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='webinfo.publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='webinfo.year'),
        ),
        migrations.AddField(
            model_name='author',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='webinfo.nation'),
        ),
        migrations.AddField(
            model_name='author',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='webinfo.year'),
        ),
    ]
