# Generated by Django 3.2.5 on 2022-04-16 04:12
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

PUBLISHERS = [
    { 'publisher_name': 'TCK Publishing',},
    { 'publisher_name': 'Reed Elsevier',},
    { 'publisher_name': 'Penguin Random House',},
    { 'publisher_name': 'Harper Collins',},
    { 'publisher_name': 'Simon & Schuster',},
    { 'publisher_name': 'Phoenix Publishing and Media Company',},
    { 'publisher_name': 'Phoenix Yard Books',},
    { 'publisher_name': 'Pan Macmillan',},
    { 'publisher_name': 'Bloomsbury',},
    { 'publisher_name': 'Arbordale Publishing',},
    { 'publisher_name': 'Arcade Publishing',},
    { 'publisher_name': 'Arcadia Publishing',},
    { 'publisher_name': 'Arkham House',},
    { 'publisher_name': 'Armida Publications',},
    { 'publisher_name': 'B & W Publishing',},
    { 'publisher_name': 'Beacon Publishing',},
    { 'publisher_name': 'John Blake Publishing',},
    { 'publisher_name': 'Capstone Publishers',},
    { 'publisher_name': 'Flame Tree Publishing',},
    { 'publisher_name': 'Morgan James Publishing',},
    { 'publisher_name': 'Manning Publications',},
    { 'publisher_name': 'Mother Tongue Publishing',},
    { 'publisher_name': 'Medknow Publications',},
    { 'publisher_name': 'Tuttle Publishing',},
    { 'publisher_name': 'Tachyon Publications',},
    { 'publisher_name': 'City Lights Publishers',},
    { 'publisher_name': 'Dover Publications',},
    { 'publisher_name': 'Graywolf Press',},
    { 'publisher_name': 'Dorrance Publishing Company',},
    { 'publisher_name': 'Gantec Publishing Solutions',},
    { 'publisher_name': 'Kensington Publishing Corp',},
    { 'publisher_name': 'Ripple Grove Press',},
    { 'publisher_name': 'North Atlantic Books',},
    { 'publisher_name': 'Wiley',},
    { 'publisher_name': 'Balboa Press',},
    { 'publisher_name': 'BookPress Publishing',},
    { 'publisher_name': 'Anchor Book Press',},
    { 'publisher_name': 'Lee & Low Books',},
    { 'publisher_name': 'The Open Book Press',},
    { 'publisher_name': 'Hidden Brook Press',},
    { 'publisher_name': 'Little Book Press',},
    { 'publisher_name': 'Lakewater Press',},
    { 'publisher_name': 'Stormbird Press',},
    { 'publisher_name': 'Autumn House Press',},
    { 'publisher_name': 'Inkwater Press',},
    { 'publisher_name': 'TouchPoint Press',},
    { 'publisher_name': 'Alchemy Press Book of Horrors',},
    { 'publisher_name': 'Tradewind Books',},
    { 'publisher_name': 'Blossom Spring Publishing',},
    { 'publisher_name': 'Queer Pack',},
    { 'publisher_name': 'Coffeetown Press',},
    { 'publisher_name': 'Eerdmans',},
    { 'publisher_name': 'Grey Book Press',},
    { 'publisher_name': 'Hydra Publications',},
    { 'publisher_name': 'Conundrum Press',},
    { 'publisher_name': 'Chelsea Green Publishing',},
    { 'publisher_name': 'House of Anansi Press',},
    { 'publisher_name': 'August House Publishers',},
    { 'publisher_name': 'blue manatee press',},
    { 'publisher_name': 'Shambhala',},
    { 'publisher_name': 'Green Frog Publishing',},
    { 'publisher_name': 'Brick Cave Media',},
    { 'publisher_name': 'Living Springs Publishers LLP',},
    { 'publisher_name': 'Korero Press',},
    { 'publisher_name': 'City Lights Press',},
    { 'publisher_name': 'eLectio Publishing',},
    { 'publisher_name': 'Weasel Press',},
    { 'publisher_name': 'Alfresco Press',},
    { 'publisher_name': 'Native Ink Press',},
    { 'publisher_name': 'Virgogray Press',},
    { 'publisher_name': 'Torquere Press',},
    { 'publisher_name': 'Pants On Fire Press',},
    { 'publisher_name': 'Figroot Press',},
    { 'publisher_name': 'CKN Christian Publishing',},
    { 'publisher_name': 'Wordpool Press',},
    { 'publisher_name': 'Ink Smith Publisher',},
    { 'publisher_name': 'Wolfpack Publishing',},
    { 'publisher_name': 'Moonshine Cove Publishing, LLC',},
    { 'publisher_name': 'WiDo Publishing',},
    { 'publisher_name': 'Mason J. Press',},
    { 'publisher_name': 'Neverland Publishing Company',},
    { 'publisher_name': 'The Key Publishing House Inc',},
    { 'publisher_name': 'Divertir Publishing',},
    { 'publisher_name': 'John Hunt Publishing',},
    { 'publisher_name': 'White Knuckle Press',},
    { 'publisher_name': 'Anthem Press',},
    { 'publisher_name': 'Writerists House',},
    { 'publisher_name': 'Lore Lush Publishing',},
    { 'publisher_name': 'Tiny Fox Press',},
    { 'publisher_name': 'Echoic Mobile Press',},
    { 'publisher_name': 'Blue Swan Publishing',},
    { 'publisher_name': 'Regal House Publishing',},
    { 'publisher_name': 'Ink Smith Publishing',},
    { 'publisher_name': 'Tirgearr Publishing',},
    { 'publisher_name': 'Triplicity Publishing',},
    { 'publisher_name': 'Coventry House Publishing',},
    { 'publisher_name': 'Sleepytown Press',},
    { 'publisher_name': 'Leo Publishing, LLC',},
    { 'publisher_name': 'Biblio Publishing',},
    { 'publisher_name': 'The Wild Rose Press',},
    { 'publisher_name': 'Eden Stories Press',},
    { 'publisher_name': 'Unhinged Publishing and Consulting',}
]


def add_publisher_data(apps, schema_editor):
    publisher_class = apps.get_model('webinfo', 'Publisher')
    for publisher in PUBLISHERS:
        try:
            duplicate_object = publisher_class.objects.get(
                publisher_name=publisher['publisher_name']
            )
            print('Duplicate publisher entry not added to publisher table:', publisher['publisher_name'])
        except ObjectDoesNotExist:
            publisher_object = publisher_class.objects.create(
                publisher_name=publisher['publisher_name']
            )


def remove_publisher_data(apps, schema_editor):
    publisher_class = apps.get_model('webinfo', 'Publisher')
    for publisher in PUBLISHERS:
        publisher_object = publisher_class.objects.get(
            publisher_name=publisher['publisher_name']
        )
        publisher_object.delete()

        
class Migration(migrations.Migration):

    dependencies = [
        ('webinfo', '0006_load_type_data'),
    ]

    operations = [
        migrations.RunPython(
            add_publisher_data,
            remove_publisher_data
        )
    ]
