# Generated by Django 3.2.5 on 2022-04-16 19:59
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

ACTIVITIES = [
    {'name':'Cardify','date':'2021-08-11','time':'10:31','address':'77 American Ash Circle','description':'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',},
    {'name':'Latlux','date':'2020-09-06','time':'12:41','address':'5 Westerfield Court','description':'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',},
    {'name':'Otcom','date':'2021-10-28','time':'17:31','address':'77 Hovde Plaza','description':'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',},
    {'name':'Veribet','date':'2021-11-25','time':'15:39','address':'615 Stang Hill','description':'Maecenas ut massa quis augue luctus tincidunt. nulla mollis molestie lorem. Quisque ut erat.',},
    {'name':'Tampflex','date':'2022-03-03','time':'13:15','address':'436 Towne Parkway','description':'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',},
    {'name':'Kanlam','date':'2020-05-26','time':'13:55','address':'1697 Tony Road','description':'Aenean fermentum. Donec ut mauris eget massa tempor convallis. nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',},
    {'name':'Wrapsafe','date':'2021-02-17','time':'17:31','address':'4 Logan Avenue','description':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',},
    {'name':'Pannier','date':'2021-06-09','time':'13:01','address':'8 Drewry Center','description':'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',},
    {'name':'Fintone','date':'2022-03-28','time':'12:44','address':'917 Esch Court','description':'NA',},
    {'name':'Sub-Ex','date':'2022-01-13','time':'12:39','address':'4 Fieldstone Point','description':'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',},
    {'name':'Home Ing','date':'2022-03-22','time':'17:53','address':'9 Cody Terrace','description':'NA',},
    {'name':'Y-find','date':'2021-12-12','time':'17:30','address':'0677 Gerald Lane','description':'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',},
    {'name':'Vagram','date':'2022-01-17','time':'13:42','address':'37739 Granby Center','description':'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',},
    {'name':'Bitchip','date':'2021-12-08','time':'11:07','address':'3194 Bellgrove Court','description':'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',},
    {'name':'Biodex','date':'2022-01-02','time':'17:21','address':'953 Twin Pines Way','description':'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',},
    {'name':'Zoolab','date':'2022-01-06','time':'12:39','address':'246 Del Mar Way','description':'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',},
    {'name':'Cardguard','date':'2021-07-21','time':'15:31','address':'077 Del Mar Terrace','description':'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',},
    {'name':'Stringtough','date':'2020-10-25','time':'11:40','address':'08180 Debs Court','description':'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',},
    {'name':'Namfix','date':'2021-10-02','time':'10:16','address':'6 Susan Court','description':'Phasellus in felis. Donec semper sapien a libero. Nam dui.',},
    {'name':'It','date':'2022-01-19','time':'11:20','address':'32389 Hovde Court','description':'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',},
    {'name':'Kanlam','date':'2021-03-29','time':'13:25','address':'6209 Hintze Street','description':'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',},
    {'name':'Zoolab','date':'2020-08-15','time':'12:59','address':'53191 Ohio Park','description':'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',},
    {'name':'Tresom','date':'2020-04-17','time':'15:17','address':'3956 Barnett Circle','description':'Sed ante. Vivamus tortor. Duis mattis egestas metus.',},
    {'name':'Gembucket','date':'2020-10-09','time':'10:25','address':'72 Duke Drive','description':'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',},
    {'name':'Prodder','date':'2021-10-17','time':'16:48','address':'9 Summit Court','description':'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',},
    {'name':'Transcof','date':'2021-02-14','time':'13:32','address':'0404 Schlimgen Terrace','description':'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',},
    {'name':'Bitwolf','date':'2020-07-02','time':'17:41','address':'37 Arizona Road','description':'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',},
    {'name':'Flowdesk','date':'2021-01-17','time':'14:52','address':'705 Carioca Center','description':'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',},
    {'name':'Konklab','date':'2022-01-26','time':'14:42','address':'6738 Monica Junction','description':'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.',},
    {'name':'Solarbreeze','date':'2021-07-22','time':'14:24','address':'2 Menomonie Way','description':'Fusce consequat. nulla nisl. Nunc nisl.',},
    {'name':'Span','date':'2020-11-10','time':'17:08','address':'4 Heffernan Alley','description':'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',},
    {'name':'Alphazap','date':'2020-11-17','time':'18:18','address':'09 Buena Vista Drive','description':'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. nullam molestie nibh in lectus.',},
    {'name':'Domainer','date':'2020-10-10','time':'15:48','address':'53676 Schurz Point','description':'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',},
    {'name':'Rank','date':'2021-07-15','time':'18:41','address':'0 Crest Line Street','description':'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',},
    {'name':'Prodder','date':'2021-10-24','time':'18:00','address':'6027 Meadow Ridge Hill','description':'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',},
    {'name':'Voltsillam','date':'2021-07-26','time':'10:36','address':'4095 Mccormick Pass','description':'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',},
    {'name':'Namfix','date':'2021-06-04','time':'15:03','address':'8 Forest Dale Crossing','description':'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',},
    {'name':'Overhold','date':'2021-10-14','time':'14:59','address':'3157 Fuller Point','description':'nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',},
    {'name':'Wrapsafe','date':'2020-10-25','time':'10:14','address':'3632 Dottie Plaza','description':'nulla ut erat id mauris vulputate elementum. nullam varius. nulla facilisi.',},
    {'name':'Voyatouch','date':'2022-01-09','time':'16:22','address':'67 Artisan Point','description':'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',},
    {'name':'Solarbreeze','date':'2021-09-17','time':'14:08','address':'81127 Quincy Drive','description':'NA',},
    {'name':'Voyatouch','date':'2022-01-05','time':'13:44','address':'989 Northland Pass','description':'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',},
    {'name':'Y-find','date':'2020-11-08','time':'17:47','address':'94 Canary Lane','description':'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',},
    {'name':'Andalax','date':'2021-08-26','time':'12:38','address':'1 Bonner Terrace','description':'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',},
    {'name':'Viva','date':'2022-03-15','time':'13:10','address':'69612 Granby Drive','description':'nulla ut erat id mauris vulputate elementum. nullam varius. nulla facilisi.',},
    {'name':'Stim','date':'2021-08-27','time':'16:47','address':'2 Fairview Hill','description':'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.',},
    {'name':'Voyatouch','date':'2022-02-14','time':'16:02','address':'32346 Derek Circle','description':'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',},
    {'name':'Fintone','date':'2020-06-28','time':'10:16','address':'16 Monterey Avenue','description':'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',},
    {'name':'Job','date':'2020-06-05','time':'10:20','address':'75 Vernon Street','description':'Phasellus in felis. Donec semper sapien a libero. Nam dui.',},
    {'name':'Regrant','date':'2021-07-09','time':'16:00','address':'34 Kensington Alley','description':'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',},
    {'name':'Treeflex','date':'2021-08-07','time':'11:18','address':'699 Carioca Lane','description':'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',},
    {'name':'Biodex','date':'2021-06-30','time':'15:27','address':'1968 Sachs Trail','description':'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',},
    {'name':'Alphazap','date':'2020-11-15','time':'10:43','address':'0 Delladonna Park','description':'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',},
    {'name':'Andalax','date':'2022-04-14','time':'13:05','address':'18448 Nova Circle','description':'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',},
    {'name':'Temp','date':'2020-08-25','time':'18:55','address':'3503 Jenna Alley','description':'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',},
    {'name':'Regrant','date':'2021-09-27','time':'10:55','address':'20718 Redwing Place','description':'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',},
    {'name':'Konklux','date':'2021-01-15','time':'11:56','address':'5814 Helena Way','description':'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',},
    {'name':'Wrapsafe','date':'2021-10-26','time':'14:47','address':'4909 Kenwood Trail','description':'nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',},
    {'name':'Vagram','date':'2020-10-14','time':'16:24','address':'7 Cottonwood Point','description':'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',},
    {'name':'Temp','date':'2020-10-28','time':'15:38','address':'8 American Terrace','description':'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',},
    {'name':'Y-Solowarm','date':'2021-10-09','time':'12:16','address':'9994 Sauthoff Alley','description':'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',},
    {'name':'Bitwolf','date':'2021-11-02','time':'15:16','address':'3 Village Green Trail','description':'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',},
    {'name':'Solarbreeze','date':'2020-12-06','time':'16:48','address':'11349 Norway Maple Pass','description':'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',},
    {'name':'Bitwolf','date':'2021-11-14','time':'10:09','address':'142 Trailsway Park','description':'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. nulla suscipit ligula in lacus.',},
    {'name':'Temp','date':'2021-07-21','time':'17:35','address':'8489 Lunder Point','description':'NA',},
    {'name':'Veribet','date':'2022-02-04','time':'18:07','address':'9 Redwing Avenue','description':'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',},
    {'name':'Flowdesk','date':'2022-04-05','time':'15:55','address':'7380 Bonner Alley','description':'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',},
    {'name':'Bytecard','date':'2021-05-01','time':'11:30','address':'2080 Farragut Lane','description':'NA',},
    {'name':'Bitwolf','date':'2021-07-15','time':'12:51','address':'67724 Red Cloud Way','description':'nulla ut erat id mauris vulputate elementum. nullam varius. nulla facilisi.',},
    {'name':'Greenlam','date':'2021-08-22','time':'13:43','address':'552 Texas Trail','description':'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',},
    {'name':'Sub-Ex','date':'2021-02-01','time':'16:36','address':'0 Cottonwood Terrace','description':'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',},
    {'name':'Veribet','date':'2020-07-19','time':'16:54','address':'3506 Bartillon Avenue','description':'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. nullam molestie nibh in lectus.',},
    {'name':'Job','date':'2021-11-29','time':'17:07','address':'5732 Blue Bill Park Drive','description':'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',},
    {'name':'Asoka','date':'2021-06-11','time':'17:42','address':'7156 Londonderry Parkway','description':'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',},
    {'name':'Overhold','date':'2021-12-31','time':'15:56','address':'18392 Welch Parkway','description':'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',},
    {'name':'Veribet','date':'2020-11-14','time':'18:29','address':'3 Gulseth Plaza','description':'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. nulla justo.',},
    {'name':'Vagram','date':'2021-01-01','time':'12:42','address':'96 Helena Circle','description':'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',},
    {'name':'Stringtough','date':'2022-03-26','time':'13:17','address':'3 Talmadge Point','description':'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',},
    {'name':'Tin','date':'2020-06-03','time':'10:53','address':'480 Division Street','description':'NA',},
    {'name':'Lotlux','date':'2021-05-03','time':'13:56','address':'378 Thackeray Circle','description':'NA',},
    {'name':'Bamity','date':'2021-10-14','time':'16:15','address':'66 Grover Road','description':'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',},
    {'name':'Kanlam','date':'2020-07-25','time':'16:59','address':'52865 Atwood Pass','description':'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',},
    {'name':'Trippledex','date':'2021-06-06','time':'14:00','address':'259 Prairieview Street','description':'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',},
    {'name':'Subin','date':'2020-11-09','time':'11:04','address':'6351 Morrow Street','description':'Fusce consequat. nulla nisl. Nunc nisl.',},
    {'name':'Holdlamis','date':'2020-06-04','time':'12:20','address':'296 Portage Hill','description':'Maecenas ut massa quis augue luctus tincidunt. nulla mollis molestie lorem. Quisque ut erat.',},
    {'name':'Fintone','date':'2021-03-04','time':'13:22','address':'0 Elgar Alley','description':'NA',},
    {'name':'Zaam-Dox','date':'2022-03-23','time':'16:26','address':'069 Morrow Hill','description':'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',},
    {'name':'Home Ing','date':'2021-07-25','time':'17:15','address':'70 Pawling Parkway','description':'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',},
    {'name':'Rank','date':'2022-03-02','time':'12:01','address':'99 Shopko Circle','description':'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',},
    {'name':'Flowdesk','date':'2020-11-04','time':'16:24','address':'96299 Red Cloud Pass','description':'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',},
    {'name':'Zaam-Dox','date':'2020-06-25','time':'13:57','address':'4830 Hoard Parkway','description':'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',},
    {'name':'Latlux','date':'2020-10-31','time':'16:03','address':'34439 Fulton Terrace','description':'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',},
    {'name':'Job','date':'2021-03-03','time':'16:54','address':'0 Main Junction','description':'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',},
    {'name':'Fixflex','date':'2022-03-30','time':'14:37','address':'7029 Lillian Center','description':'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. nulla justo.',},
    {'name':'Otcom','date':'2021-07-27','time':'16:46','address':'9676 Portage Circle','description':'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. nulla justo.',},
    {'name':'Fintone','date':'2021-05-13','time':'11:18','address':'394 Dwight Pass','description':'nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',},
    {'name':'Overhold','date':'2021-12-13','time':'18:38','address':'40 Moose Trail','description':'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',},
    {'name':'Job','date':'2020-08-25','time':'15:18','address':'64533 Charing Cross Place','description':'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',},
    {'name':'Biodex','date':'2021-12-22','time':'12:42','address':'31475 Knutson Point','description':'Aenean fermentum. Donec ut mauris eget massa tempor convallis. nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',},
    {'name':'Bytecard','date':'2021-09-10','time':'11:58','address':'829 Haas Lane','description':'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',}
]


def add_activity_data(apps, schema_editor):
    activity_class = apps.get_model('webinfo', 'Activity')
    for activity in ACTIVITIES:
        try:
            duplicate_object = activity_class.objects.get(
                name=activity['name'],
                date=activity['date'],
                time=activity['time'],
                address=activity['address'],
                description=activity['description']
            )
            print('Duplicate activity entry not added to activity table:', activity['name'])
        except ObjectDoesNotExist:
            activity_object = activity_class.objects.create(
                name=activity['name'],
                date=activity['date'],
                time=activity['time'],
                address=activity['address'],
                description=activity['description']
            )


def remove_activity_data(apps, schema_editor):
    activity_class = apps.get_model('webinfo', 'Activity')
    for activity in ACTIVITIES:
        activity_object = activity_class.objects.get(
            name=activity['name'],
            date=activity['date'],
            time=activity['time'],
            address=activity['address'],
            description=activity['description']
        )
        activity_object.delete()
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('webinfo', '0008_load_systemuser_data'),
    ]

    operations = [
        migrations.RunPython(
            add_activity_data,
            remove_activity_data
        )
    ]
